# Generated by Django 5.0.6 on 2024-06-09 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50)),
                ('cus_ph', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50)),
                ('guest', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('request', models.TextField(max_length=300)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.venue')),
            ],
        ),
    ]
